root: false
env: { browser: true, es2020: true }
extends:
    - "eslint:recommended"
    - "airbnb-typescript"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:react-hooks/recommended"
ignorePatterns: ["dist", ".eslintrc.cjs"]
parser: "@typescript-eslint/parser"
plugins: ["react-refresh"]
rules:
    "react-refresh/only-export-components":
        ["warn", { allowConstantExport: true }]
    "react/jsx-indent": ["error", 4]
    "react/jsx-indent-props": ["error", 4]
    "react/jsx-props-no-spreading": "off"
    "react/react-in-jsx-scope": "off"
    "react/require-default-props": "off"
    "@typescript-eslint/indent": ["error", 4]
    "@typescript-eslint/quotes": ["error", "double"]
    "@typescript-eslint/no-shadow": "off"
    "@typescript-eslint/comma-dangle": "off"
    "import/no-extraneous-dependencies": "off"
    "import/no-cycle": "off"
    "jsx-a11y/label-has-associated-control": "off"
