# syntax=docker/dockerfile:1
FROM node:16-alpine

WORKDIR /app

COPY ["./package.json", "./package-lock.json*", "./"]

RUN npm install

COPY ["./public", "./public"]
COPY ["./src", "./src"]

EXPOSE 3000/tcp

CMD ["npm", "start"]
