root: false
env: { browser: true, es2020: true }
extends:
    - "eslint:recommended"
    - "plugin:jest/recommended"
    - "plugin:node/recommended"
ignorePatterns:
    ["dist", ".eslintrc.cjs", "db/migrations/*.js", db/models/index.js]
rules:
    node/no-unsupported-features/es-syntax: off
    node/no-unsupported-features/node-builtins: off
    import/no-extraneous-dependencies: ["error", { devDependencies: true }]
overrides:
    - files:
          - "**/*.test.js"
      rules:
          jest/expect-expect: off
          no-console: off
          node/no-unpublished-require:
              ["error", { allowModules: ["supertest"] }]
