# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]

jobs:
    build:
        environment: production
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Write .env to build
              env:
                  BUILD_PATH: '${{ env.BUILD_PATH }}'
                  COURIER_AUTH_TOKEN: '${{ env.COURIER_AUTH_TOKEN }}'
                  NODE_ENV: '${{ env.NODE_ENV }}'
                  PORT: '${{ env.PORT }}'
                  REACT_APP_API_ROOT: '${{ env.REACT_APP_API_ROOT }}'
                  REACT_APP_DOMAIN_ROOT: '${{ env.REACT_APP_DOMAIN_ROOT }}'

              run: |
                  echo $BUILD_PATH > .env
                  echo $COURIER_AUTH_TOKEN >> .env
                  echo $NODE_ENV >> .env
                  echo $PORT >> .env
                  echo $REACT_APP_API_ROOT >> .env
                  echo $REACT_APP_DOMAIN_ROOT >> .env
                  cat .env
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: Install dependencies and build
              run: npm run dist
