# This is a basic workflow to help you get started with Actions

name: Deploy node-test-site

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the production branch
#   push:
#     branches: [ production ]
#   pull_request:
#     branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ~/node-test-site/
            git pull
            npm run install-all
            npm run build
            cd ~
            chmod -R c4patino:www-data
            chown -R 775
            pm2 restart node-test-site
